### PR TITLE
Fix macOS compile of scorecomp.cpp: cast size_t to uint64_t for TextStream

### LINKED ISSUE #33987: Unit tests fail to compile on macOS: ambiguous TextStream::operator<< in scorecomp.cpp
### Issue type
Other type of issue (build / compile error)

### Description with steps to reproduce
Building the unit tests on macOS fails to compile `src/engraving/tests/utils/scorecomp.cpp`. It compiles on Linux.

Steps:
1. On macOS (Apple Clang), configure with `MUSE_ENABLE_UNIT_TESTS=ON`.
2. Build the `engraving_tests` target.

Actual: compilation fails with
```
src/engraving/tests/utils/scorecomp.cpp:219:22: error: use of overloaded operator '<<' is ambiguous (with operand types 'TextStream' and 'const size_t' (aka 'const unsigned long'))
muse/framework/global/serialization/textstream.h:52:17: note: candidate function: TextStream& operator<<(int32_t)
muse/framework/global/serialization/textstream.h:53:17: note: candidate function: TextStream& operator<<(uint32_t)
muse/framework/global/serialization/textstream.h:55:17: note: candidate function: TextStream& operator<<(int64_t)
muse/framework/global/serialization/textstream.h:56:17: note: candidate function: TextStream& operator<<(uint64_t)
```
The same error repeats on lines 221, 223 and 225.

Expected: the unit tests compile on macOS, as they do on Linux.

### In which versions of MuseScore Studio is this issue present?
Current `main` development build (5.0.0), since PR #33822. Not present in released 4.x.

### Regression
Yes, this works in the latest released version and is broken in the nightly builds.

### Operating system
macOS 26.5.1 (Apple Clang, arm64)

### Additional context
The unit tests are compiled only by `check_unit_tests.yml` on `ubuntu-24.04`; the macOS job builds the app bundle with unit tests disabled, so this file is never compiled on macOS in CI. Introduced by PR #33822 (`ebcbb5eba6`).

### Checklist
- [x] This report follows the guidelines for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the issue tracker for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by manolo**
Resolves: #33987

`ScoreComp::compareFiles` writes `size_t` diff-header values into a `muse::TextStream`, which has no `size_t` overload, so on macOS the call is ambiguous and the unit tests fail to compile. Cast the four values to `uint64_t` at the call sites. No behaviour change (on Linux it already resolved to the `uint64_t` overload).

- [x] I signed the [CLA](https://musescore.org/en/cla) (regular contributor)
- [x] The title of the PR describes the problem it addresses.
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves.
- [x] The code in the PR follows the coding rules.
- [x] I understand all aspects of the code I'm contributing and I'm able to explain it if requested.
- [x] The code compiles and runs on my machine. I have manually tested and verified that my changes fulfil their intended purpose.
- [x] No prior attempts to resolve this problem exist.
- [x] There are no unnecessary changes.
- [x] I created a unit test or vtest to verify the changes I made (if applicable). Not applicable: compile-only fix; the existing engraving tests now build on macOS.

### CODE REVIEW

**Comment by rpatters1** [comment]
In my opinion, [this PR](https://github.com/musescore/muse_framework/pull/100) in `muse` is a more comprehensive fix and will get rid of the need for ugly casting in `<<` sequences.

**Review by RomanPudashkin — APPROVED** [review]

**Comment by RomanPudashkin** [comment]
Merging this PR as a temporary solution (until Casper's PR is merged)
