### PR TITLE
fix #281472: MuseScore 3 does not run on macOS 10.10 & 10.11

### PR DESCRIPTION
**Pull request by mattmcclinch**
Resolves: https://musescore.org/en/node/281472.

The bug in Qt <= 5.9.7 that results in a crash is triggered by adding an old `QMenu` object back into the menu bar after the menu bar has been cleared. This prevents the crash by only adding new `QMenu` objects to the menu bar. 

Some menus have an object name—set with `setObjectName()`—and some do not. For the ones that do, after the menu is recreated it is given the same object name as the old menu.

The code that sets the menu titles has been moved out of `MuseScore::retranslate()` into a new function`MuseScore::setMenuTitles()` so that the newly created menus can be given their proper titles without having to retranslate everything.

Now the `MuseScore` class maintains references to the “Stretch” menu and the “Debug” menu (if applicable) so that they can be given their proper titles after the menus are recreated.

Now `Workspace::menuToStringList` only contains the menus that are present in the current workspace.

In order for the `MuseScore` class to be able to maintain accurate references to the menu objects, `Workspace::findMenuFromString()`—which was previously a private method—has been made public.

Travis once again uses Qt 5.9.3 to build the package for macOS.

The macOS Deployment target has been changed to 10.10.

### CODE REVIEW

**Comment by anatoly-os** [comment]
@mattmcclinch this is awesome. You are awesome! :)

Btw, Qt 5.12.x is the only version we should use. Qt 5.12 is believed to work correctly with macOS 10.10 and 10.11 despite on the statement in the docs. We didn't support it because of the bug you seemed to fix. So, we can keep using Qt 5.12. Using Qt 5.9.x will probably make it possible to run MuseScore 3 on macOS 10.9 and 10.8 (probably 10.7).

**Comment by mattmcclinch** [comment]
> Qt 5.12 is believed to work correctly with macOS 10.10 and 10.11

All evidence points to the contrary. If MuseScore is built with Qt 5.12, when I try to run it on macOS 10.11, I get this output:

dyld: Symbol not found: _kSecAttrKeyTypeECSECPrimeRandom
  Referenced from: /Applications/MuseScore 3.app/Contents/MacOS/../Frameworks/QtWebEngineCore.framework/Versions/5/QtWebEngineCore (which was built for Mac OS X 10.12)
  Expected in: /System/Library/Frameworks/Security.framework/Versions/A/Security
 in /Applications/MuseScore 3.app/Contents/MacOS/../Frameworks/QtWebEngineCore.framework/Versions/5/QtWebEngineCore
Trace/BPT trap: 5

and the application does not load. This suggests that the minimum deployment target for Qt 5.12 is macOS 10.12, and any application built with Qt 5.12 will not run on anything lower.

The purpose of this patch was to make it safe to build MuseScore with Qt 5.9 so that it could run on any macOS >= 10.10. If we are not going to build MuseScore with Qt 5.9, then there is no reason to apply this patch. However, instead of modifying the existing Travis job, we could create a new Travis job that uses Qt 5.9 to make a separate build that targets macOS 10.10 & 10.11.

**Comment by RobFog** [comment]
I would love to be able to use MuseScore 3.

**Comment by riaanvn** [comment]
@anatoly-os , there has been no movement on this for 2 months. Can you please reward @mattmcclinch's awesomeness by merging this? 
Is there anything that still prevents you from doing so?

**Comment by anatoly-os** [comment]
@mattmcclinch thank you! I manually applied the changes related to menus and workspaces in 968ca5e45855aeef55d747887734cfbf444de399
