### PR TITLE
Link with private Qt modules, to make build with Qt 6.10 passes

### PR DESCRIPTION
**Pull request by sarunint**
Based on #30667 by @doronbehar 

While trying to build MuseScore Studio with Qt 6.10, I came across multiple build failures regarding to imports of private Qt modules.

After some researching, this is caused by these 2 Qt changes
- [CMake: Split off private module config packages](https://codereview.qt-project.org/c/qt/qtbase/+/611583)
- [CMake: Only load Qt6FooPrivate automatically when building Qt](https://codereview.qt-project.org/c/qt/qtbase/+/615004)

In short, MuseScore, as a consumer of Qt, needs to be explicitly linked with `Qt6FooPrivate` modules in order to be successfully built.

Edit 2025-10-23 1310 UTC: I've also removed the `set(MODULE_INCLUDE_PRIVATE ${Qt6Gui_PRIVATE_INCLUDE_DIRS} )` calls in these areas, since we now explicitly linked with the private modules.

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [ ] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Comment by doronbehar** [comment]
Thanks for the PR. It seems much more mature then mine. I still experience this failure with it (applied upon `v4.6.2`):

```
FAILED: [code=1] src/importexport/midi/CMakeFiles/iex_midi.dir/Unity/unity_1_cxx.cxx.o 
/nix/store/x8mydcgbry214s802nzvy7fdljx404ym-gcc-wrapper-14.3.0/bin/g++ -DKORS_LOGGER_QT_SUPPORT -DKORS_PROFILER_ENABLED -DMUE_BUILD_ENGRAVING_DEVTOOLS -DNDEBUG -DQT_CORE5COMPAT_LIB -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_QMLINTEGRATION_LIB -DQT_QMLMETA_LIB -DQT_QMLMODELS_LIB -DQT_QMLWORKERSCRIPT_LIB -DQT_QML_LIB -DQT_QUICK_LIB -DQT_SUPPORT -DQT_WIDGETS_LIB -DSCRIPT_INTERFACE -DSYSTEM_TINYXML -Dbeatroot_QML_IMPORT=\"\" -Dengraving_QML_IMPORT=\"\" -Diex_midi_QML_IMPORT=\"\" -Dmuse_global_EXPORTS=1 -Dmuse_global_QML_IMPORT=\"\" -I/build/source/build/src/importexport/midi -I/build/source/src/importexport/midi -I/build/source/build/src/importexport/midi/iex_midi_autogen/include -I/build/source/build -I/build/source/src -I/build/source -I/build/source/framework -I/build/source/framework/global -I/build/source/framework/testing/thirdparty/googletest/googletest/include -I/build/source/src/framework -I/build/source/src/framework/global -I/build/source/src/framework/testing/thirdparty/googletest/googletest/include -I/build/source/src/engraving -isystem /nix/store/r7wdw4nkkjii690wwnzkgj68cg4shh2v-qtbase-6.10.0/include/QtCore -isystem /nix/store/r7wdw4nkkjii690wwnzkgj68cg4shh2v-qtbase-6.10.0/mkspecs/linux-g++ -isystem /nix/store/r7wdw4nkkjii690wwnzkgj68cg4shh2v-qtbase-6.10.0/include/QtGui -isystem /nix/store/rz0lc8irp5knfzwakm86p3ifkflr1w1i-qtdeclarative-6.10.0/include/QtQuick -isystem /nix/store/rz0lc8irp5knfzwakm86p3ifkflr1w1i-qtdeclarative-6.10.0/include/QtQml -isystem /nix/store/rz0lc8irp5knfzwakm86p3ifkflr1w1i-qtdeclarative-6.10.0/include/QtQmlIntegration -isystem /nix/store/r7wdw4nkkjii690wwnzkgj68cg4shh2v-qtbase-6.10.0/include/QtNetwork -isystem /nix/store/rz0lc8irp5knfzwakm86p3ifkflr1w1i-qtdeclarative-6.10.0/include/QtQmlMeta -isystem /nix/store/rz0lc8irp5knfzwakm86p3ifkflr1w1i-qtdeclarative-6.10.0/include/QtQmlModels -isystem /nix/store/rz0lc8irp5knfzwakm86p3ifkflr1w1i-qtdeclarative-6.10.0/include/QtQmlWorkerScript -isystem /nix/store/r7wdw4nkkjii690wwnzkgj68cg4shh2v-qtbase-6.10.0/include/QtOpenGL -isystem /nix/store/r7wdw4nkkjii690wwnzkgj68cg4shh2v-qtbase-6.10.0/include/QtWidgets -isystem /nix/store/y4cxchgai8fm5rw8z6lgfw80hv2342ws-qt5compat-6.10.0/include/QtCore5Compat -O3 -DNDEBUG -std=gnu++17 -Wall -Wextra -fPIC -Winvalid-pch -include /build/source/build/src/framework/global/CMakeFiles/muse_global.dir/cmake_pch.hxx -MD -MT src/importexport/midi/CMakeFiles/iex_midi.dir/Unity/unity_1_cxx.cxx.o -MF src/importexport/midi/CMakeFiles/iex_midi.dir/Unity/unity_1_cxx.cxx.o.d -o src/importexport/midi/CMakeFiles/iex_midi.dir/Unity/unity_1_cxx.cxx.o -c /build/source/build/src/importexport/midi/CMakeFiles/iex_midi.dir/Unity/unity_1_cxx.cxx
In file included from /nix/store/r7wdw4nkkjii690wwnzkgj68cg4shh2v-qtbase-6.10.0/include/QtCore/qglobal.h:33,
                 from /nix/store/r7wdw4nkkjii690wwnzkgj68cg4shh2v-qtbase-6.10.0/include/QtCore/qnamespace.h:12,
                 from /nix/store/r7wdw4nkkjii690wwnzkgj68cg4shh2v-qtbase-6.10.0/include/QtCore/qobjectdefs.h:12,
                 from /nix/store/r7wdw4nkkjii690wwnzkgj68cg4shh2v-qtbase-6.10.0/include/QtCore/qobject.h:10,
                 from /nix/store/r7wdw4nkkjii690wwnzkgj68cg4shh2v-qtbase-6.10.0/include/QtCore/QObject:1,
                 from /build/source/buildscripts/pch/pch.h:74,
                 from /build/source/build/src/framework/global/CMakeFiles/muse_global.dir/cmake_pch.hxx:5,
                 from <command-line>:
/build/source/src/importexport/midi/internal/midiimport/importmidi_tuplet.cpp: In function 'void mu::iex::midi::MidiTuplet::addTupletEvents(std::multimap<mu::iex::midi::ReducedFraction, TupletData>&, const std::vector<TupletInfo>&, const std::__cxx11::list<TiedTuplet>&)':
/build/source/src/importexport/midi/internal/midiimport/importmidi_tuplet.cpp:900:59: error: 'message' was not declared in this scope
  900 |                            "MidiTuplet::addTupletEvents", message.toLatin1().data());
      |                                                           ^~~~~~~
```

**Comment by sarunint** [comment]
> Thanks for the PR. It seems much more mature then mine. I still experience this failure with it (applied upon `v4.6.2`):
> 
> ```
> FAILED: [code=1] src/importexport/midi/CMakeFiles/iex_midi.dir/Unity/unity_1_cxx.cxx.o 
> /nix/store/x8mydcgbry214s802nzvy7fdljx404ym-gcc-wrapper-14.3.0/bin/g++ -DKORS_LOGGER_QT_SUPPORT -DKORS_PROFILER_ENABLED -DMUE_BUILD_ENGRAVING_DEVTOOLS -DNDEBUG -DQT_CORE5COMPAT_LIB -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_QMLINTEGRATION_LIB -DQT_QMLMETA_LIB -DQT_QMLMODELS_LIB -DQT_QMLWORKERSCRIPT_LIB -DQT_QML_LIB -DQT_QUICK_LIB -DQT_SUPPORT -DQT_WIDGETS_LIB -DSCRIPT_INTERFACE -DSYSTEM_TINYXML -Dbeatroot_QML_IMPORT=\"\" -Dengraving_QML_IMPORT=\"\" -Diex_midi_QML_IMPORT=\"\" -Dmuse_global_EXPORTS=1 -Dmuse_global_QML_IMPORT=\"\" -I/build/source/build/src/importexport/midi -I/build/source/src/importexport/midi -I/build/source/build/src/importexport/midi/iex_midi_autogen/include -I/build/source/build -I/build/source/src -I/build/source -I/build/source/framework -I/build/source/framework/global -I/build/source/framework/testing/thirdparty/googletest/googletest/include -I/build/source/src/framework -I/build/source/src/framework/global -I/build/source/src/framework/testing/thirdparty/googletest/googletest/include -I/build/source/src/engraving -isystem /nix/store/r7wdw4nkkjii690wwnzkgj68cg4shh2v-qtbase-6.10.0/include/QtCore -isystem /nix/store/r7wdw4nkkjii690wwnzkgj68cg4shh2v-qtbase-6.10.0/mkspecs/linux-g++ -isystem /nix/store/r7wdw4nkkjii690wwnzkgj68cg4shh2v-qtbase-6.10.0/include/QtGui -isystem /nix/store/rz0lc8irp5knfzwakm86p3ifkflr1w1i-qtdeclarative-6.10.0/include/QtQuick -isystem /nix/store/rz0lc8irp5knfzwakm86p3ifkflr1w1i-qtdeclarative-6.10.0/include/QtQml -isystem /nix/store/rz0lc8irp5knfzwakm86p3ifkflr1w1i-qtdeclarative-6.10.0/include/QtQmlIntegration -isystem /nix/store/r7wdw4nkkjii690wwnzkgj68cg4shh2v-qtbase-6.10.0/include/QtNetwork -isystem /nix/store/rz0lc8irp5knfzwakm86p3ifkflr1w1i-qtdeclarative-6.10.0/include/QtQmlMeta -isystem /nix/store/rz0lc8irp5knfzwakm86p3ifkflr1w1i-qtdeclarative-6.10.0/include/QtQmlModels -isystem /nix/store/rz0lc8irp5knfzwakm86p3ifkflr1w1i-qtdeclarative-6.10.0/include/QtQmlWorkerScript -isystem /nix/store/r7wdw4nkkjii690wwnzkgj68cg4shh2v-qtbase-6.10.0/include/QtOpenGL -isystem /nix/store/r7wdw4nkkjii690wwnzkgj68cg4shh2v-qtbase-6.10.0/include/QtWidgets -isystem /nix/store/y4cxchgai8fm5rw8z6lgfw80hv2342ws-qt5compat-6.10.0/include/QtCore5Compat -O3 -DNDEBUG -std=gnu++17 -Wall -Wextra -fPIC -Winvalid-pch -include /build/source/build/src/framework/global/CMakeFiles/muse_global.dir/cmake_pch.hxx -MD -MT src/importexport/midi/CMakeFiles/iex_midi.dir/Unity/unity_1_cxx.cxx.o -MF src/importexport/midi/CMakeFiles/iex_midi.dir/Unity/unity_1_cxx.cxx.o.d -o src/importexport/midi/CMakeFiles/iex_midi.dir/Unity/unity_1_cxx.cxx.o -c /build/source/build/src/importexport/midi/CMakeFiles/iex_midi.dir/Unity/unity_1_cxx.cxx
> In file included from /nix/store/r7wdw4nkkjii690wwnzkgj68cg4shh2v-qtbase-6.10.0/include/QtCore/qglobal.h:33,
>                  from /nix/store/r7wdw4nkkjii690wwnzkgj68cg4shh2v-qtbase-6.10.0/include/QtCore/qnamespace.h:12,
>                  from /nix/store/r7wdw4nkkjii690wwnzkgj68cg4shh2v-qtbase-6.10.0/include/QtCore/qobjectdefs.h:12,
>                  from /nix/store/r7wdw4nkkjii690wwnzkgj68cg4shh2v-qtbase-6.10.0/include/QtCore/qobject.h:10,
>                  from /nix/store/r7wdw4nkkjii690wwnzkgj68cg4shh2v-qtbase-6.10.0/include/QtCore/QObject:1,
>                  from /build/source/buildscripts/pch/pch.h:74,
>                  from /build/source/build/src/framework/global/CMakeFiles/muse_global.dir/cmake_pch.hxx:5,
>                  from <command-line>:
> /build/source/src/importexport/midi/internal/midiimport/importmidi_tuplet.cpp: In function 'void mu::iex::midi::MidiTuplet::addTupletEvents(std::multimap<mu::iex::midi::ReducedFraction, TupletData>&, const std::vector<TupletInfo>&, const std::__cxx11::list<TiedTuplet>&)':
> /build/source/src/importexport/midi/internal/midiimport/importmidi_tuplet.cpp:900:59: error: 'message' was not declared in this scope
>   900 |                            "MidiTuplet::addTupletEvents", message.toLatin1().data());
>       |                                                           ^~~~~~~
> ```

Yeah, that issue is unrelated. It's fixed by #30422.

Somehow the fix is not backported to both 4.6.2 and 4.6.3, or the official AppImage is built with `QT_DEBUG` turned on.

**Comment by doronbehar** [comment]
Thanks for the link. With both patches applied the compilation works for me with Qt 6.10 . I hope it works with Qt 6.9 too. If upstream uses it in the CI, it should be OK.

**Comment by cbjeukendrup** [comment]
> Somehow the fix is not backported to both 4.6.2 and 4.6.3, or the official AppImage is built with `QT_DEBUG` turned on.

We don't back-port things automatically when we're not asked to, but if you open a PR to the 4.6.3 branch, we'll merge it to 4.6.4 when the 4.6.4 branch is created.

It's indeed unexpected that `QT_DEBUG` is apparently defined in our release builds, given that we don't define `QT_DEBUG` ourselves, we use `add_compile_definitions($<$<NOT:$<CONFIG:Debug>>:QT_NO_DEBUG>)` and Qt has 
```c++
#if !defined(QT_NO_DEBUG) && !defined(QT_DEBUG)
#  define QT_DEBUG
#endif
```
Maybe `$<CONFIG:Debug>` evaluates to true for RelWithDebugInfo builds too, but that seems unlikely to me.

**Comment by PPN-SD** [comment]
KDockwidgets has already its patch for it https://github.com/KDAB/KDDockWidgets/pull/615

**Comment by cbjeukendrup** [comment]
But we're using an old and customised version of KDDW (which we plan to address eventually, but that will be a huge task)
