### ISSUE TITLE
MuseScore 3.5 Release Candidate. PRs to be merged

### ISSUE THREAD

**Issue by anatoly-os** [musescore/MuseScore#6195]
- [x] #5508

**Comment by shoogle** [comment]
- [ ] #6210 - fixes bugs/regressions introduced by #6173

**Comment by Marr11317** [comment]
[ ] #6208

**Comment by Spire42** [comment]
* [ ]  #6213 - [Canvas: impossible to choose a custom zoom default, difficult to override in toolbar](https://musescore.org/en/node/306598)

Fixes bugs and regressions introduced in #5623 and #6186.

**Comment by Jojo-Schmitz** [comment]
* [ ] #6218

**Comment by worldwideweary** [comment]
#6223 - Fix Crash Case with Empty Trailing Measure command (https://musescore.org/en/node/306807)

**Comment by tobik** [comment]
* [ ]  #6224 - [Fix #306821: Regression TAB and number of lines in collision avoidance of rests](https://musescore.org/en/node/306821)

**Comment by MarcSabatella** [comment]
Still not totally clear on the criteria for what is being considered, but to me these are good candidates.  They are not regressions (well, not new regressions in 3.5 anyhow) but they do address some real pain points that are easily solved.  And they don't involve new strings or otherwise require new documentation, they just allow things to work that people have every right to expect to work anyhow.

- [ ] (https://github.com/musescore/MuseScore/pull/6238)[allow Ctrl+Delete from note input mode]
- [ ] (https://github.com/musescore/MuseScore/pull/6232)[Rhythm note input mode fixes and improvements]
- [ ] (https://github.com/musescore/MuseScore/pull/6207)[insert horizontal frame in front of frame using palette]
- [ ] (https://github.com/musescore/MuseScore/pull/6204)[Reimplement Shift+L/R for leading space while in edit mode upon notehead]

**Comment by MarcSabatella** [comment]
Another issue with no PR yet, I'm soliciting feedback on the best way to proceed:

- [ ] (Chord symbol playback enabled for one user not enabled by another)[https://musescore.org/en/node/307005]

**Comment by tobik** [comment]
#6243 - restore backward compatibility for collision avoidance of rests

**Comment by jeetee** [comment]
[ ] #6248 fix issues with jumps and repeats (no regression, just plain bugfixing)

**Comment by AntonioBL** [comment]
- [ ] https://github.com/musescore/MuseScore/pull/6246 - [[Windows, Linux] Bold and underlined text is not displayed properly](https://musescore.org/en/node/307075) - a regression introduced by the workaround of PR #5794. This new PR simply disables the workaround for the bold+underlined case.

**Comment by shoogle** [comment]
- [ ] #6249 - fix Save Online on Linux

**Comment by lvinken** [comment]
[#6256](https://github.com/musescore/MuseScore/pull/6256) low risk MusicXML import/export improvements

**Comment by Spire42** [comment]
* [ ]  #6258 - [Revert default zoom type to “100%”](https://musescore.org/en/node/307121)

By popular demand. Undoes the change to the default zoom type that was made in #5623.

**Comment by worldwideweary** [comment]
#6260 - [Element dragging with modifier keys [ctrl/shift] incorrectly apply offsets of previous drags](https://musescore.org/en/node/307077)

**Comment by rettinghaus** [comment]
#6263

**Comment by lvinken** [comment]
[#6269 - Musescore crashes when loading .mxl file containing incomplete tuplet](https://github.com/musescore/MuseScore/pull/6269)

**Comment by MarcSabatella** [comment]
I edited a comment above to list #6268 (changes default playback sound for chord symbols to piano) as the consensus on how to handle compatibility/surprise concerns for older scores with chord symbol playback.

**Comment by Jojo-Schmitz** [comment]
Yet unresolved issues:

* Updating the MuseScore Genereal (and MuseScore General HQ) soundfont
    solves several issues
    * [#305308: Marching band snare drum cymbals don't sound](https://musescore.org/en/node/305308) (this issue also has the links to the updated soundfonts)
    * [#299545: Incorrect Harmonica Range](https://musescore.org/en/node/299545)
    * [#299366: Choir sample on E3-F#3 adds octave pitch](https://musescore.org/en/node/299366)
    * [#291501: use of envelope delay phase in SoundFont causes bizarre playback behavior](https://musescore.org/en/node/291501)
    * [#232886: MuseScore_General.sf3: "Space Voice" panning issue.](https://musescore.org/en/node/232886)

**Comment by MarcSabatella** [comment]
- [ ] #6280 - recent regression where Ctrl+Delete would become disabled after right-click

**Comment by CodeforEvolution** [comment]
- [ ] #6283 - Add support for the Haiku operating system

This would really help to have this added to the 3.5 release, as it would make it easier for the folks over at HaikuPorts (Haiku’s main package management repo).

**Comment by MarcSabatella** [comment]
- [ ] #6297 - fixes a 3.5 regression caused by #5747

**Comment by Jojo-Schmitz** [comment]
* [ ] #6267  - fix a warning reg. a no longer existing tabStop, minor but harmless
* [ ] #6296 - [fix #307548: Lines palette: duplicate symbols](https://musescore.org/en/node/307548) Not a regression, but a very small and harmless fix

**Comment by Howard-C** [comment]
#6265 - Partially fix #294768: tremolos don't have cue size
This PR also fixes an issue of the stem length becoming a bit longer than necessary for chords with tremolo strokes and a downward stem.

**Comment by Jojo-Schmitz** [comment]
* [ ] Y offsets change when stave space is changed

**Comment by Jojo-Schmitz** [comment]
I'd like to see this PR in 3.5RC:

* [ ] #6307 - [fix #276141: no space for lyrics in continuous view](https://musescore.org/en/node/276141)

**Comment by MarcSabatella** [comment]
No PR yet, but this is a serious regression that needs to be fixed:

- [ ] https://musescore.org/en/node/307721 (blank lines ignored at top of text)

**Comment by MarcSabatella** [comment]
I believe this is important for 3.5, otherwise people will employ workarounds that will break when this does get fixed:

- [ ] #6321

**Comment by Jojo-Schmitz** [comment]
> No PR yet, but this is a serious regression that needs to be fixed:
> 
> * [ ]  https://musescore.org/en/node/307721 (blank lines ignored at top of text)

* [ ] #6328 - [fix #307721: blank lines ignored at top of text](https://musescore.org/en/node/307721)

**Comment by Jojo-Schmitz** [comment]
* [ ] #6330 - [Fix #307741 images attached to measures don't propagate between score and existing parts](https://musescore.org/en/node/307741)

**Comment by Jojo-Schmitz** [comment]
* [ ] #6247  (is in 3.x, but not yet in 3.5rc)

**Comment by anatoly-os** [comment]
Congratulations with 3.5 Release Candidate! https://musescore.org/en/3.5rc
