### ISSUE TITLE
[MSVC] MuseScore failed to run 3 tests under on release and debug configuration

### ISSUE THREAD

**Issue by QuellaZhang** [musescore/MuseScore#33489]
### Issue type

Choose option...

### Description with steps to reproduce

Hi All,

MuseScore failed to run 3 tests on release and debug configuration with MSVC on windows. It can be reproduced on e8df477 commit on main branch. Could you please help look at this issue?

**Failed tests:**
```
	  1 - muse_global_tests (Failed)
	 22 - engraving_tests (Failed)
	 31 - iex_musicxml_tests (Failed)
```

**Repro steps:**

1. git clone https://github.com/musescore/MuseScore.git C:\gitP\musescore\MuseScore
2. cd C:\gitP\musescore\MuseScore
3. mkdir build && cd build_amd64
4. download "https://s3.amazonaws.com/utils.musescore.org/dependencies.7z to C:\gitP\musescore\MuseScore\dependencies
5. pip install aqtinstall
6. python -m aqt install-qt windows desktop 6.10.2 win64_msvc2022_64 --modules qtshadertools qt5compat qtnetworkauth qtscxml --outputdir C:\Qt
7. cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.26100.0  -DBUILD_UNIT_TESTS=ON -DMUE_COMPILE_QT5_COMPAT=ON -DCMAKE_PREFIX_PATH="C:\Qt\6.10.2\msvc2022_64" ..
8. msbuild /m /p:Platform=x64 /p:Configuration=Release MuseScore.sln /t:Rebuild
9. set PATH=C:\Program Files\Git\usr\bin;%PATH%
10. set PATH=C:\Qt\6.10.2\msvc2022_64\bin;%PATH%
11. set PATH=C:\gitP\musescore\MuseScore\dependencies\libx64;%PATH%
12. set QT_PLUGIN_PATH=C:\Qt\6.10.2\msvc2022_64\plugins
13. ctest --build-config Release --output-on-failure -R "muse_global_tests|engraving_tests|iex_musicxml_tests"

### Supporting files, videos and screenshots

Test log:  [Test (2).log](https://github.com/user-attachments/files/28037818/Test.2.log)

**Some error infos:**

<img width="1895" height="618" alt="Image" src="https://github.com/user-attachments/assets/13109865-e0c7-47e9-aa33-5616ba5982f5" />

<img width="1367" height="177" alt="Image" src="https://github.com/user-attachments/assets/0f56e4c9-df53-4935-97f4-26f1d6d5de68" />

### In which versions of MuseScore Studio is this issue present?

Main branch latest version

### Regression

No.

### Operating system

Windows 11

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by Jojo-Schmitz** [comment]
One of the failing MusicXL tests have been disabled in c58f62a026, all others seem to pass now (on GutHub CI, which uses Linux for the tests?

Actually IIRC the tests never really worked on MSVC, and https://github.com/musescore/MuseScore/wiki/Fix-the-CI-checks#building-the-unit-tests-locally recommends using QtCreator.
Would be quite nice though if they did.

**Comment by QuellaZhang** [comment]
Thanks for the quick reply, we couldn't switch to QTCreator, so I disabled these tests locally.

In addition, I also found a compilation error, `ERROR`, which conflicts with the macros in the Windows header file, causing `Code::ERROR` to `Code::0`, So, I added a patch to fix this issue.

```
diff --git a/muse/framework/ui/view/iconcodes.h b/muse/framework/ui/view/iconcodes.h
index bc62ac40c..0f47a4c91 100644
--- a/muse/framework/ui/view/iconcodes.h
+++ b/muse/framework/ui/view/iconcodes.h
@@ -31,8 +31,8 @@
 #ifdef INFO
 #undef INFO
 #endif
-#ifdef ERROR
-#undef ERROR
+#ifdef ERROR_ICON
+#undef ERROR_ICON
 #endif
 #ifdef QUESTION
 #undef QUESTION
@@ -340,7 +340,7 @@ enum class Code : char16_t {
 
     WARNING = 0xF3CE,
     INFO = 0xF3CF,
-    ERROR = 0xF3D0,
+    ERROR_ICON = 0xF3D0,
     QUESTION = 0xF3D1,
 
     MUTE = 0xF3D5,
```

**Comment by Jojo-Schmitz** [comment]
Please PR that patch, this isn't the 1st time such an ERROR turns up

**Comment by QuellaZhang** [comment]
@Jojo-Schmitz , submitted PR https://github.com/musescore/muse_framework/pull/48.

**Comment by QuellaZhang** [comment]
Update. The `ERROR` conflict issue has been fixed upstream.

**Comment by Jojo-Schmitz** [comment]
So this issue here can get closed, right?

**Comment by QuellaZhang** [comment]
Feel free to close this issue since I have disabled the failing tests locally.

**Comment by RomanPudashkin** [comment]
Fixed in 

https://github.com/musescore/muse_framework/pull/56
https://github.com/musescore/muse_framework/pull/54
https://github.com/musescore/MuseScore/pull/33617
https://github.com/musescore/MuseScore/pull/33580
