### PR TITLE
Compile tests with Qt 5.12.0

### PR DESCRIPTION
**Pull request by lasconic**

### CODE REVIEW

**Comment by lasconic** [comment]
Looks like Qt 5.9.7 doesn't work well on Ubuntu Trusty... We might need to go to Xenial... but that's a lot more work...

**Comment by Jojo-Schmitz** [comment]
Maybe better to directly jump to Qt 5.12, which is available as an RC meanwhile, finale release due 5Dec18.
I think I've managed to convince @anatoly-os to release MuseScore 3.0 Beta with that ;-)

**Comment by lasconic** [comment]
Since Qt 5.12.0 is out, let's try.

**Comment by mirabilos** [comment]
`bionic` (18.04 LTS) has Qt 5.9 and is my tentative “lowest target” for MuseScore 3 Debian packages, FWIW. (In Debian, `buster` (10) with Qt 5.11 or _perhaps_ (but unlikely) 5.12 will be it.)

**Comment by mirabilos** [comment]
That being said, the mtests don’t compile with Qt 5.9 / bionic (Qt 5.11 / cosmic is OK):

    undefined reference to `bool QTest::qCompare<unsigned int, unsigned long>(unsigned int const&, unsigned long const&, char const*, char const*, char const*, int)'

(and possibly others)

I’ve disabled them for the PPA builds, for now.
