### ISSUE TITLE
Compiling with recent versions of g++

### ISSUE THREAD

**Issue by csillag** [musescore/MuseScore#6229]
I am trying to build myself a local version of MuseScore on a modern Debian system.

The local version of the C++ compiler is: `g++ (Debian 9.3.0-13) 9.3.0`

When running the build, I get this:
```
make[3]: Entering directory '/mnt/user_data/home/csillag/MuseScore/build.release'
[ 55%] Building CXX object mscore/CMakeFiles/mscoreapp.dir/mscoreapp_autogen/mocs_compilation.cpp.o
[ 55%] Building CXX object mscore/CMakeFiles/mscoreapp.dir/qrc_musescorefonts-Campania_qmlcache.cpp.o
[ 55%] Building CXX object mscore/CMakeFiles/mscoreapp.dir/qrc_musescore_qmlcache.cpp.o
[ 55%] Building CXX object mscore/CMakeFiles/mscoreapp.dir/qrc_musescorefonts-Bravura_qmlcache.cpp.o
[ 55%] Building CXX object mscore/CMakeFiles/mscoreapp.dir/qrc_musescorefonts-MuseJazz_qmlcache.cpp.o
[ 55%] Building CXX object mscore/CMakeFiles/mscoreapp.dir/qrc_musescorefonts-MScore_qmlcache.cpp.o
[ 55%] Building CXX object mscore/CMakeFiles/mscoreapp.dir/qrc_musescorefonts-Gootville_qmlcache.cpp.o
[ 55%] Building CXX object mscore/CMakeFiles/mscoreapp.dir/qrc_qml_qmlcache.cpp.o
In file included from /home/csillag/MuseScore/build.release/mscore/mscoreapp_autogen/XD3YLU7WXD/moc_loginmanager_p.cpp:9,
                 from /home/csillag/MuseScore/build.release/mscore/mscoreapp_autogen/mocs_compilation.cpp:10:
/home/csillag/MuseScore/mscore/cloud/loginmanager_p.h:141:1: error: expected class-name before ‘{’ token
  141 | {
      | ^
/home/csillag/MuseScore/mscore/cloud/loginmanager_p.h:146:27: error: ‘QWebEngineUrlRequestInfo’ has not been declared
  146 |     void interceptRequest(QWebEngineUrlRequestInfo& info) override;
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~
/home/csillag/MuseScore/mscore/cloud/loginmanager_p.h:146:10: error: ‘void Ms::ApiWebEngineRequestInterceptor::interceptRequest(int&)’ marked ‘override’, but does not override
  146 |     void interceptRequest(QWebEngineUrlRequestInfo& info) override;
      |          ^~~~~~~~~~~~~~~~
/home/csillag/MuseScore/mscore/cloud/loginmanager_p.h: In constructor ‘Ms::ApiWebEngineRequestInterceptor::ApiWebEngineRequestInterceptor(QObject*)’:
/home/csillag/MuseScore/mscore/cloud/loginmanager_p.h:145:11: error: class ‘Ms::ApiWebEngineRequestInterceptor’ does not have any field named ‘QWebEngineUrlRequestInterceptor’
  145 |         : QWebEngineUrlRequestInterceptor(parent) {}
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

I haven't modified the source code, nor have I tweaked the build config, so I guess the reason must be related to the version of the C++ compiler, and the dialect it speaks by default.

I have also g++-6 and g++-8 and hand which I could try, but I don't see anything in the documentation about configuring the compiler used.

So could you please point me into the right direction?
(Either by telling me how to compile with the gcc-9.3, or telling me how to set it up to use older gcc+?)

Thank you.

**Comment by csillag** [comment]
I was wondering that maybe it's just the latest branch, but now I tried v3.5beta, and it also fails to compile...

**Comment by Jojo-Schmitz** [comment]
Please report this in the forums or issue tracker on musescore.org, or in the telegram developers' chat. We're not using the GutHub issue tracker (not for this purpose anyway)

**Comment by Jojo-Schmitz** [comment]
Athough stuff that refers to webengine may indicat thate you forgot to install that Qt component or forgot to disable it in the CMake config

**Comment by csillag** [comment]
Yes, it was that, indeed. 

(It would have been easier for me to spot this if there was  a pause between the "configure" and the "make" phase, as it it customary in the old `./configure`; `make` system.)

Thanks for the tip, now it works OK.
